version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install pip-licenses

  build:
    commands:
      - pip install -r requirements.txt
      - pip-licenses --format=json --output-file=licenses.json

artifacts:
  files:
    - licenses.json

post_build:
  commands:
    - aws s3 cp licenses.json s3://$S3_BUCKET_NAME/licenses.json
