version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install license-checker  # Install license-checker or any other tool
      - python license_checker.py  # Run your license checking script
      
      # Upload license info to S3 bucket
      - aws s3 cp licenses.json s3://flask-app-licenses/flask-app-build/licenses.json
