version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install pip-licenses

  build:
    commands:
      - pip install -r requirements.txt
      - pip-licenses --format=json --output-file=licenses.json

  post_build:
    commands:
      - REQUIRED_PACKAGES=$(<requirements.txt)
      - |
        python - <<EOF
        import json

        required_packages = set(${REQUIRED_PACKAGES}.split())
        
        with open("licenses.json", "r") as f:
            licenses_data = json.load(f)
        
        filtered_licenses = [pkg for pkg in licenses_data if pkg["Name"] in required_packages]
        
        with open("filtered_licenses.json", "w") as f:
            json.dump(filtered_licenses, f, indent=2)
        EOF
      - aws s3 cp filtered_licenses.json s3://$S3_BUCKET_NAME/filtered_licenses.json
