version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Creating virtual environment
      - python -m venv venv
      - echo Listing files in current directory
      - ls -al
      - echo Listing files in venv directory
      - ls -al venv
      - echo Listing files in venv/bin directory
      - ls -al venv/bin
      - echo Activating virtual environment
      - . venv/bin/activate || source venv/bin/activate
      - echo Virtual environment activated
      - echo Upgrading pip
      - pip install --upgrade pip
      - echo Installing dependencies
      - pip install -r requirements.txt
      - echo Installing pip-licenses
      - pip install pip-licenses

  build:
    commands:
      - echo Generating licenses.json
      - pip-licenses --from=mixed --format=json --output-file=licenses.json

artifacts:
  files:
    - licenses.json

post_build:
  commands:
    - echo Copying licenses.json to S3
    - aws s3 cp licenses.json s3://your-s3-bucket-name/licenses.json
