version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install pip-licenses

  build:
    commands:
      - pip install -r requirements.txt
      - pip-licenses --format=json --output-file=licenses.json

  post_build:
    commands:
      - |
        python3 - <<EOF
        import json

        # Read requirements.txt to get required packages
        with open('requirements.txt', 'r') as f:
            required_packages = {line.strip() for line in f if line.strip()}

        # Load licenses.json data
        with open('licenses.json', 'r') as f:
            licenses_data = json.load(f)

        # Filter licenses.json based on required packages
        filtered_licenses = [pkg for pkg in licenses_data if pkg['Name'] in required_packages]

        # Write filtered data to filtered_licenses.json
        with open('filtered_licenses.json', 'w') as f:
            json.dump(filtered_licenses, f, indent=2)

        # Upload filtered_licenses.json to S3 bucket
        import boto3
        s3 = boto3.client('s3')
        with open('filtered_licenses.json', 'rb') as data:
            s3.upload_fileobj(data, '$S3_BUCKET_NAME', 'filtered_licenses.json')
        EOF
