version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip  # Ensure pip is up-to-date
      - pip install license-checker || true  # Try installing license-checker, continue on failure
      
  build:
    commands:
      - python license_checker.py  # Run your license checking script
      - aws s3 cp licenses.json s3://flask-app-licenses/flask-app-build/licenses.json
