version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies
      - python -m venv venv
      - ls -al  # List files in the root directory for verification
      - ls -al venv  # List files in the venv directory for verification
      - . venv/bin/activate || source venv/bin/activate  # Activate the virtual environment
      - echo Virtual environment activated
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pip-licenses
      - echo Checking installed packages
      - pip list  # Verify installed packages for troubleshooting

  build:
    commands:
      - echo Generating licenses.json
      - pip-licenses --from=mixed --format=json --output-file=licenses.json

artifacts:
  files:
    - licenses.json

post_build:
  commands:
    - echo Copying licenses.json to S3
    - aws s3 cp licenses.json s3://flask-app-licenses/licenses.json
    - echo Build completed successfully

