version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - python -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pip-licenses

  build:
    commands:
      - pip-licenses --from=mixed --format=json --output-file=licenses.json

artifacts:
  files:
    - licenses.json

post_build:
  commands:
    - aws s3 cp licenses.json s3://your-s3-bucket-name/licenses.json
