version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install pip-licenses

  pre_build:
    commands:
      - pip install -r Requirements.txt
      - pip-licenses --format=json --output-file=licenses.json

  build:
    commands:
      - echo "Starting Python script execution..."
      - python3 build_script.py

artifacts:
  files:
    - filtered_licenses.json
