version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g npm@latest
  build:
    commands:
      - npm audit --json --verbose > audit_results.json || true
      - echo "Uploading licensing information to S3"
      - aws s3 cp audit_results.json s3://flask-app-licenses/flask-app-build/licenses.json
