version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g license-checker  # Install license-checker globally
      - npm install  # Install project dependencies
  
  build:
    commands:
      - node license_checker.js  # Run your license checking script
      
      # Upload filtered license info to S3 bucket
      - aws s3 cp licenses.json s3://flask-app-licenses/flask-app-build/licenses.json
