version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - |
        retry_count=5
        until [[ $retry_count -le 0 ]]; do
          pip install --upgrade pip
          if [ $? -eq 0 ]; then
            break
          fi
          ((retry_count--))
          sleep 5
        done
      
      - pip install license-checker || true  # Continue installation even if license-checker fails
  
  build:
    commands:
      - python license_checker.py  # Run your license checking script
      - aws s3 cp licenses.json s3://flask-app-licenses/flask-app-build/licenses.json
